
spring:
    shardingsphere:
        datasource:
            common:
                driver-class-name: com.mysql.cj.jdbc.Driver
                password: mUP36j6,GTqZRJiNNjc7
                type: com.zaxxer.hikari.HikariDataSource
                username: root
            names: ds00,ds01
            ds00:
                jdbc-url: jdbc:mysql://localhost:3306/ds00?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
            ds01:
                jdbc-url: jdbc:mysql://localhost:3306/ds01?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        rules:
            sharding:
                key-generators:
                    snowflake:
                        props:
                            worker-id: 123
                        type: SNOWFLAKE
                sharding-algorithms:
                    database-inline:
                        props:
                            algorithm-expression: ds0$->{user_id % 2}
                        type: INLINE
                    table-inline:
                        props:
                            algorithm-expression: t_order_$->{id % 16}
                        type: INLINE
                tables:
                    t_order:
                        actual-data-nodes: ds0$->{0..1}.t_order_$->{0..15}
                        database-strategy:
                            standard:
                                sharding-algorithm-name: database-inline
                                sharding-column: user_id
                        table-strategy:
                            standard:
                                sharding-algorithm-name: table-inline
                                sharding-column: order_no


